# Simple custom yazi config file that only displays a single pane
# To use this in Zide, make sure ZIDE_USE_YAZI_CONFIG is not set to false
[manager]
ratio = [1, 1, 1]

[opener]
edit = [
	{ run = '$EDITOR "$@"', block = true, for = "unix" },
	{ run = "%EDITOR% %*",  block = true, for = "windows" },
]
